config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items 
  resources :histories, only: [:index,]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'LBグレー' },
    { id: 3, name: 'LBレッド' },
    { id: 4, name: '白' },
    { id: 5, name: '黒' },
    { id: 6, name: 'キアカ' },
    { id: 7, name: 'N3グレー' },
    { id: 8, name: 'N4グレー' },
    { id: 9, name: 'HSCブルー' },
    { id: 10, name: 'プライマー' },
    { id: 11, name: 'サビコート' },
    { id: 12, name: '硬化剤3k' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :paint
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :history

  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :color

  validates :color_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  has_many :items
  has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @items = Item.all.order('created_at DESC')
  end

  private

  def history_params
    params.require(:history).permit(:color_id).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @items = Item.all.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @history = @item.history
  end

  private

  def item_params
    params.require(:item).permit(:color_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/histories/index.html.erb
<div class="history-contents">

  <div class="history-main">
    <h2 class="history-title">塗料持ち出し履歴</h2>

    <table class="history-table">
      <thead>
        <tr>
          <th>持ち出し日</th>
          <th>標準色</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.created_at.strftime('%Y-%m-%d') %></td>
          <td><%= item.color.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="back-btn-contents">
      <%= link_to 'トップページに戻る', root_path, class: "back-btn" %>
    </div>
  </div>

</div>

app/views/items/index.html.erb
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, root_path, class: "user-nickname"  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"  %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

<%= link_to(new_item_path, class: 'paint-btn') do %>
  <span class='paint-btn-text'>新規塗料記録</span>
<% end %>

<%= link_to(histories_path, class: 'paint-btn') do %>
  <span class='paint-btn-text'>塗料持ち出し履歴</span>
<% end %>

app/views/items/new.html.erb
<div class="items-sell-contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">塗料の情報を入力</h2>


    <%= form_with model: @item, local: true do |f| %>


    <%= render 'devise/shared/error_messages', resource: @item %>


    <%# 持ち出した塗料の入力 %>
    <div class="items-paint">
      <div class="weight-bold-text">塗料</div>
      <div class="form">
        <div class="weight-bold-text">
          標準色
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:color_id, Color.all, :id, :name, {}, {class:"select-box", id:"item-color"}) %>
        
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">

      <%=link_to 'もどる', root_path, class:"back-btn" %>
      <%= f.submit "保存する" ,class:"sell-btn" %>
      
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paintman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>